### ISSUE TITLE
Tool is not compliant with Package Storage v2

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-integration-corpus-generator-tool#26]
Hi @aspacca,

To be honest I accidentally came to this place and after a quick look at the source code, I noticed that the tool uses Arbitrary File API to access package resources. Unfortunately, we will limit the API to expose only static resources like docs, images, etc., but no manifests, fields, or Kibana saved objects.

It seems this will break the tool, so I just wanted to raise awareness. You should modify the source code to pull the .zip package first and extract artifacts from it.

**Comment by aspacca** [comment]
hi @mtojek thanks for the heads up

**Comment by joshdover** [comment]
We'll need to start pulling the full archive to grab these files. Considering horde's usage of this tool, it's very likely that caching the archive or the relevant contents will be important

**Comment by aspacca** [comment]
fixed on #34
