### ISSUE TITLE
Generating date with proper format (or format generic dates)

### ISSUE THREAD

**Issue by endorama** [elastic/elastic-integration-corpus-generator-tool#44]
Working on https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/43 I needed to create 2 dates with specific format: a ISO8601 compliant timestamp and a Syslog compliant timestamp.

In both cases (from my understanding) this cannot be expressed in our templates. 

In Elasticsearch `date` type fields can set a [`format`](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html) parameter to specify date format, but this is not supported in this tool (not sure it **should** be, as this parameter applies to index field mapping).

A viable solution would be to format dates in the template itself (separating generation and presentation, something @aspacca and me discussed and which we consider a bonus point of the template approach recently introduced).

This tool includes [Masterminds/sprig](https://github.com/Masterminds/sprig) templating functions, but only "pure" ones ([here](https://github.com/elastic/elastic-integration-corpus-generator-tool/blob/a86918989bd2dc8389a91bb597ec5b860961fa67/pkg/genlib/generator_with_text_template.go#L34) we are mapping only "hermetic functions"). [These functions](https://github.com/Masterminds/sprig/blob/581758eb7d96ae4d113649668fa96acc74d46e7f/functions.go#L70) **do not** include `date`.

Following this, I'm not sure how to move forward in the linked PR, or what is the suggested approach for custom dates in templates. Can we rethink the exclusion of non hermetic functions and add them too?

**Comment by aspacca** [comment]
> A viable solution would be to format dates in the template itself (separating generation and presentation, something @aspacca and me discussed and which we consider a bonus point of the template approach recently introduced).
> 
> This tool includes [Masterminds/sprig](https://github.com/Masterminds/sprig) templating functions, but only "pure" ones ([here](https://github.com/elastic/elastic-integration-corpus-generator-tool/blob/a86918989bd2dc8389a91bb597ec5b860961fa67/pkg/genlib/generator_with_text_template.go#L34) we are mapping only "hermetic functions"). [These functions](https://github.com/Masterminds/sprig/blob/581758eb7d96ae4d113649668fa96acc74d46e7f/functions.go#L70) **do not** include `date`.

formatting the date in the template it's the approach I use:

You don't need the `date` function from sprig (while we can discuss if adding all the functions from the package and not nly the hermetic ones): if you have a field of type `date`, using the go text/template a `time.Time` will be generated, that you can call on the `Format` method

see for example:
```
{{ $eventIngested := generate "EventIngested" }} "ingested": "{{ $eventIngested.Format "2006-01-02T15:04:05.999999Z07:00" }}"
```

**Comment by endorama** [comment]
Working as intended! I will follow-up this issue with a PR to add some documentation around this. Thanks Andrea!
