### ISSUE TITLE
Refactor `cardinality`

### ISSUE THREAD

**Issue by aspacca** [elastic/elastic-integration-corpus-generator-tool#75]
The `cardinality` setting in the config was intended to be able to generate repeated values for a given field.
Initially the value was defined as a permille of the total number of events generated: this means that if you have a `cardinality` of "10" and "1000" events generated, only "10" different values will be generated for a given field, and if you generated "2000" events, "20" different values will be generated for the same field.
With the refactoring happened in https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/15 the behaviour changed: the value was indicating the total different values to generate as a ratio between the `cardinality` value and "1000": meaning that "10" will generate "100" different values, and "20" will generated "50" different values, regardless the number of total events generated.

In https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/46 we refactored `cardinality` in order to be able to set a custom `denominator`, so that we were not forced to express a ratio based on "1000": this was functional to the fact that you might need to express relationship between different fields cardinalities that might not have a zero reminder when divided by "10" (it's specifically meaningful when you have cardinality on fields with an enum different from 2 and 5)

Still this refactoring did not introduced back the option to express the cardinality dynamically as a factor of the total number of events generated.

My proposal is to refactor the `cardinality` field once again in order to express both the original behaviour and the new one (both are useful in my opinion and we should provide all of them).

`cardinality` setting will now accept two different schemas:
1.
```
cardinality:
  fixed: X
```

This is just a different way of expressing the current behaviour: "generate X different values for the field". There's no need to express this value as a ratio between a numerator and a denominator.
If the cardinality is expressed this way we will generate X amount of different values for the field. If the number of events generated is less than X, we will generate less different values.
The X values are generated sequentially: every X events the values sequence will repeat itself. If the number of total events generated divided by X has no zero reminder, the last repeated sequence will contain less than X values.

2.
```
cardinality:
  numerator: X
  denominator: Y
```

This is the current schema, but it will change the behaviour: "generate X/Y of the total number of events different values".
If the cardinality is expressed this way we will generate N amount of different values for the field where `N = (tot events / Y) * X`.
If you set "10" as `numerator` and "100" as `denominator` and you generate "1000" total events, "100" different values will be generated. With the same settings, generating "1500" total events, will produce "150" different values.
If the number of events to generate is infinite the behaviour will be the following: "generate X/Y different values for the field", basically reproducing the actual behaviour and falling back to the behaviour of 1., just expressing X as X/Y.
If the formula `N = (tot events / Y) * X` returns anything `<1` we generate only 1 different value.
The N values are generated sequentially: every N events the values sequence will repeat itself. If the number of total events generated divided by N has no zero reminder, the last repeated sequence will contain less than N values. This might happen since N might not be an integer and we will floor N to the nearest integer.

Note:
> If the number of total events generated divided by N has no zero reminder, the last repeated sequence will contain less than N values. This might happen since N might not be an integer and we will floor N to the nearest integer.

We might change the way we calculate the total number of events to generate so that we make them with zero reminder if divided by each of the Ns (as 2.) and Xs (as 1.) resulting as parsing the config. This means that you cannot generate less events than the minimum required to fulfil every cardinality configured.
We might decide on this later on: the refactoring proposed in this issue can proceed without defining this detail. In case we will adopt nothing should change in the code dealing with cardinality, but just in the functions (one for each template engine) that calculate the total number of events to be generated.

cc @endorama, @ruflin

**Comment by endorama** [comment]
> My proposal is to refactor the cardinality field once again in order to express both the original behaviour and the new one (both are useful in my opinion and we should provide all of them).

I agree with this, 👍 from me.

> cardinality setting will now accept two different schemas:

I fear this will create confusion, may we choose to use 2 different fields instead (`fixed_cardinality` and `cardinality` maybe?)?

> This is the current schema, but it will change the behaviour: 

May you clarify what is the current behaviour and what does it change here? I'm a bit confused how would the current behaviour change.

What do you think about splitting this issue in two: one for adding `fixed` and one for refactoring `numerator/denominator` logic? Could this be done? Adding `fixed` (or whatever we decide to name it) seems a low hanging fruit, compared to the change in behaviour.

> We might change the way we calculate the total number of events to generate so that we make them with zero reminder if divided by each of the Ns (as 2.) and Xs (as 1.) resulting as parsing the config. This means that you cannot generate less events than the minimum required to fulfil every cardinality configured.

I like this and would open a separate issue to keep track of it. We may want to discuss if being strict (cannot create less events than) or relaxed (will warn user this is happening) or allowing the user to choose through a flag (like `--relaxed`).

**Comment by aspacca** [comment]
> > cardinality setting will now accept two different schemas:
> 
> I fear this will create confusion, may we choose to use 2 different fields instead (`fixed_cardinality` and `cardinality` maybe?)?

I don't know honestly: it is the same feature that can behave in two different ways.
Having a single settings with two different configuration schemas seems less confusing to me than having two different separate settings for the same feature: potentially they can be set both at the same time and produce "weird" expectations.

It would be an "anyOf" constraint for the setting, that I see not so uncommon and cleaner than "eitherOf" between two different settings.



> > This is the current schema, but it will change the behaviour:
> 
> May you clarify what is the current behaviour and what does it change here? I'm a bit confused how would the current behaviour change.

from 
```
generate `numerator`/`denominator` different values
```
to
```
generate (`total number of events` / `denominator`) * `numerator` different values
```

> What do you think about splitting this issue in two: one for adding `fixed` and one for refactoring `numerator/denominator` logic? Could this be done? Adding `fixed` (or whatever we decide to name it) seems a low hanging fruit, compared to the change in behaviour.

no problem on doing this. but after we add `fixed` and before we will refactor the `numerator/denominator` logic they will behave the same way.
since `fixed` is just a different way of expressing the same behaviour:
```
generate `numerator`/`denominator` different values
```
as
```
generate `fixed` different values
```


> I like this and would open a separate issue to keep track of it. We may want to discuss if being strict (cannot create less events than) or relaxed (will warn user this is happening) or allowing the user to choose through a flag (like `--relaxed`).

I totally agree: the topic is much broader, while it has an impact on `cardinality`, I just mentioned that for the impact itself
But I think we should discuss this last topic before making any progress on the `numerator/denominator` logic. Since it can also be the case that we decide for a strategy where we just won't new upfront how many events we will generate, an so the 
```
generate (`total number of events` / `denominator`) * `numerator` different values
```
cannot be applied

I personally would be fine to lose such feature if calculating the total number of events upfront is not reliable enough (currently the outcome of can be 2x of the required size, that's way too much) or it will require too much complexity/latency to be reliable enough

**Comment by endorama** [comment]
> potentially they can be set both at the same time and produce "weird" expectations.

This is true in either way. I think this requires adding an explicit validation step that inform the user about this cases, as it can create confusion and issues in each way we can implement it.

> but after we add fixed and before we will refactor the numerator/denominator logic they will behave the same way.

That's expected, and also why we want to introduce the `num/den` refactoring :D so :+1: from me.

> But I think we should discuss this last topic before making any progress on the numerator/denominator logic. Since it can also be the case that we decide for a strategy where we just won't know upfront how many events we will generate,

At the moment we compute this information. Postponing this decision may risk moving everything far in the future. As we have a plan now and it's sensible, I suggest to move forward and postponing the discussion on removing the total number of events computation. We are not in a hurry to take that decision and both are reversible.
